package com.elfennani.ledgerly.domain.usecase

import com.elfennani.ledgerly.domain.model.Group
import com.elfennani.ledgerly.domain.repository.GroupRepository
import javax.inject.Inject

class CreateGroupUseCase @Inject constructor(private val groupRepository: GroupRepository) {
    suspend operator fun invoke(name: String) {
        val newGroup = Group(
            id = 0, // ID will be auto-generated by the database
            name = name,
            collapsed = false
        )
        groupRepository.insertGroup(newGroup)
    }
}